config/routes.rb
Rails.application.routes.draw do
	root :to => "feeds#index"
  	get 'feed' => 'feeds#getrss'
  	resources :feeds
end

app/models/feed.rb
class Feed < ActiveRecord::Base
	validates :desc, presence: true
	validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  require 'rss'

  def getrss
    if params[:category] != nil
      if params[:category] == "all"
        @feeds = Feed.all.order("entrydate DESC")
      else
        @feeds = Feed.where(category: params[:category]).order("entrydate DESC")
      end
    elsif
      @feeds = Feed.all.order("entrydate DESC")
    end
    render "feeds/index"
  end




  # GET /feeds
  # GET /feeds.json
  def index
    lists = [
          'http://news.livedoor.com/topics/rss/top.xml',
          'http://news.livedoor.com/topics/rss/dom.xml',
          'http://news.livedoor.com/topics/rss/int.xml',
          'http://news.livedoor.com/topics/rss/eco.xml',
          'http://news.livedoor.com/topics/rss/ent.xml',
          'http://news.livedoor.com/topics/rss/spo.xml',
          'http://news.livedoor.com/rss/summary/52.xml',
          'http://news.livedoor.com/topics/rss/gourmet.xml',
          'http://news.livedoor.com/topics/rss/love.xml',
          'http://news.livedoor.com/topics/rss/trend.xml'];
        return false unless lists

        lists.each do |rss|
            rssdata = RSS::Parser.parse(rss)
            puts "_______________________
            "
            puts rss
            puts "_______________________

            "

            rssdata.items.each do |entry|
                tmpdate = entry.respond_to?(:pubDate) ? entry.pubDate : entry.dc_date
                item = Feed.new
                icategory = rss.split(/\//)[5]
                item.category = icategory.split(/\./)[0]
                puts item.category
                item.title = entry.title
                entryDesc = []
                entry.description.scan(/<li>(.+)<\/li>|<br \/>(.+)<a href=/).each do |m|
                  entryDesc.push(m)
                end
                item.desc = entryDesc.join
                item.link = entry.link
                item.entrydate = tmpdate
                puts item.category
                if item.desc =~ /....../
                  item.save
                end
            end
        end
    @feeds = Feed.all.order("entrydate DESC")
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    ######## スクレピング ########

    require 'nokogiri'
    require 'open-uri'
    require 'cgi'

    # スクレイピング先のURL
    url = @feed.link
    # Request the HTML before parsing
    html = open(url).read
    # Replace original DOCTYPE with a valid DOCTYPE
    html = html.sub(/^<!DOCTYPE html(.*)$/, '<!DOCTYPE html>')
    # Parse
    doc = Nokogiri::HTML(html)
    @doc = doc.css('.articleBody').text.split(" ")


    ######## 形態素解析 ########

    # 必要なライブラリを呼び出し。
    require 'natto'
    # nm(納豆めかぶ)を呼び出し。
    nm = Natto::MeCab.new

    common_words = []
    # nmにテキストをフィードしてparse(解析)してもらう
    nm.parse("#{@feed.desc}") do |n|
      s = n.surface ? n.surface : "-"
      common_words << s
    end
    #２文字以上の単語のみ取得
    common_twowords = []
    common_words.each do |common|
      if common.length > 1
        common_twowords.push("#{common}")
      end
    end

    title_words = []
    # nmにテキストをフィードしてparse(解析)してもらう
    nm.parse("#{@feed.title}") do |n|
      s = n.surface ? n.surface : "-"
      title_words << s
    end
    #２文字以上の単語のみ取得
    title_twowords = []
    title_words.each do |common_title|
      if common_title.length > 1
        puts common_title
        title_twowords.push("#{common_title}")
      end
    end

    #ディスクリプションをすべて取得
    feedall = Feed.all
    #feed.idとマッチ回数を入れる連想配列を作成
    relation_feed = {}
    #取得したフィードのディスクリプションをループ
    feedall.each do |feedone|

      
      # 同じカテゴリに優遇
      if @feed.category == feedone.category
        match_count = 5
      else
        match_count = 0
      end

      #文章の検証
      common_twowords.each do |common_twoword|
        # 文章とマッチ
        match_count = match_count + feedone.desc[0,90].scan(/#{common_twoword}/).size*2
      end

      #タイトルの検証
      title_twowords.each do |title_twoword|
        # タイトルとマッチ
        match_count = match_count + feedone.title.scan(/#{title_twoword}/).size*5
      end

      relation_feed.store("#{feedone.id}","#{match_count}")
    end
    # 並べ替え
    relation_feed_top = relation_feed.sort {|(k1, v1), (k2, v2)| v2 <=> v1 }

    i = 0
    @relation_feeds = []
    loop{
      relation_feed = Feed.where(id: "#{relation_feed_top[i][0]}")
      @relation_feeds.push(relation_feed)
      i += 1
      if i > 2 then
        break
      end
    }


  end



  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params[:feed]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<div class="main">
  <div class="wrap">
  <% @feeds.each do |feed| %>
    <a href=<%= "/feeds/#{feed.id}" %>>
      <div class="feed">
        <h2><%= feed.title %></h2>
        <p class="date"><%= feed.entrydate %></p>
        <p class="desc"><%= feed.desc %></p>
        <p class="link">詳しく見る</p>
      </div>
    </a>
  <% end %>
  </div>
</div>



<script type="text/javascript" >
  jQuery(function() {
    var nav = jQuery('.nav');
    var main = jQuery('.main');

    // メニューのtop座標を取得する
    var offsetTop = nav.offset().top;

    var floatMenu = function() {
        // スクロール位置がメニューのtop座標を超えたら固定にする
        if (jQuery(window).scrollTop() > offsetTop) {
            nav.addClass('fixed');
            main.addClass('fixed_main');
        } else {
            nav.removeClass('fixed');
            main.removeClass('fixed_main');
        }
    }
    jQuery(window).scroll(floatMenu);
    jQuery('body').bind('touchmove', floatMenu);
});
</script>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<div class="wrap">
	<h1 class="feed_title"><%= @feed.title %></h1>
	<p class="entrydate"><%= @feed.entrydate %></p>

	<div class="feed_content">
		<%= @doc.each do |doc| %>
			<%= doc %><br><br>
		<% end %>
	</div>

	<br><br>
	<p>元の記事を読む</p>
	<a href="<%= @feed.link %>" class="feed_link"><%= @feed.link %></a>
	<br><br>


<h2 class="relational_title">関連記事</h2>
<% @relation_feeds.each do |relation_feed| %>
	<a href="/feeds/<%= relation_feed[0].id %>">
		<div class="feed">
        	<h2><%= relation_feed[0].title %></h2>
        	<p class="date"><%= relation_feed[0].entrydate %></p>
        	<p class="desc"><%= relation_feed[0].desc %></p>
        	<p class="link">詳しく見る</p>
		</div>
	</a>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsrss</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="wrap">
  	<a href="/feeds">
	    <h1>Line Intern RSS-Reader　
	    <% if params[:category] == "all" %>全て 
	    <% elsif params[:category] == "top" %>主要
	    <% elsif params[:category] == "dom" %>国内
	    <% elsif params[:category] == "int" %>海外
	    <% elsif params[:category] == "eco" %>IT 経済
	    <% elsif params[:category] == "ent" %>芸能
	    <% elsif params[:category] == "spo" %>スポーツ
	    <% elsif params[:category] == "52" %>映画
	    <% elsif params[:category] == "gourmet" %>グルメ
	    <% elsif params[:category] == "love" %>女子
	    <% elsif params[:category] == "trend" %>トレンド
	    <% end %>
	    </h1>
	</a>
  </div>
</div>
<div class="nav">
  
  <ul>
  <div class="wrap">
      <li><%= link_to '全て', feeds_path(category: "all") %></li>
      <li><%= link_to '主要', feed_path(category: "top") %></li>
      <li><%= link_to '国内', feed_path(category: "dom") %></li>
      <li><%= link_to '海外', feed_path(category: "int") %></li>
      <li><%= link_to 'IT 経済', feed_path(category: "eco") %></li>
      <li><%= link_to '芸能', feed_path(category: "ent") %></li>
      <li><%= link_to 'スポーツ', feed_path(category: "spo") %></li>
      <li><%= link_to '映画', feed_path(category: "52") %></li>
      <li><%= link_to 'グルメ', feed_path(category: "gourmet") %></li>
      <li><%= link_to '女子', feed_path(category: "love") %></li>
      <li><%= link_to 'トレンド', feed_path(category: "trend") %></li>
      </div>
    </ul>
</div>

<%= yield %>


</body>
</html>